config/routes.rb
Rails.application.routes.draw do
  mount API::Base => '/api'

  devise_for :users
  resources :news, :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "news#index"
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/base.rb
module API
	class Base < Grape::API
		mount API::V1::Base
	end
end

app/controllers/api/v1/base.rb
module API
	module V1
		class Base < Grape::API
			mount API::V1::Data
		end
	end
end

app/controllers/api/v1/data.rb
module API
	module V1
		class Data < Grape::API
			version 'v1'
			format :json

			resource :news do 
				desc "Return all news"
					get do 
						News.all
					end
			end

			resource :users do 
				desc "Return all users"
				get do 
					User.all
				end
			end

		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
	def index
    @news = News.page(params[:page]).per(2)
  end

  private

    def news_params
      params.require(:news).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lol</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>


<h1>Listing News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.text %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>
<%= paginate @news %>
<%= page_entries_info @news %>

<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @news.text %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>